name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Create all builds for various platforms
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [ {os : 'windows', arch: 'amd64'}, {os: 'linux', arch: 'arm64' }, {os: 'linux', arch: 'amd64' }]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Confirm Version
      run: go version

    - name: Build 
      run: |
        GOOS=${{ matrix.targets.os }} GOARCH=${{ matrix.targets.arch }} go build -o SonarrTorrentCleaner_${{ matrix.targets.os }}-${{ matrix.targets.arch }}

